server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: room-service
          uri: http://localhost:9001
          predicates:
            - Path=/rooms/**

        - id: booking-service
          uri: http://localhost:9002
          predicates:
            - Path=/bookings/**
